export const GET_ERRORS = "GET_ERRORS";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const GET_PROFILE = "CREATE_PROFILE";
export const PROFILE_LOADING = "PROFILE_LOADING";
export const GET_COURSES = "GET_COURSES";
export const COURSES_LOADING = "COURSES_LOADING";
